# Generated by Django 3.0.4 on 2020-03-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256)),
                ('access_token', models.CharField(max_length=256)),
                ('ccid', models.CharField(max_length=256)),
            ],
        ),
    ]
